# Generated by Django 4.1.4 on 2022-12-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdCars', '0002_car_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
