# Generated by Django 4.1.4 on 2022-12-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdCars', '0006_company_remove_car_modelname_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='bdCars.company'),
        ),
    ]
